/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./UserManagement.module.css";

function UserTable() {
  const users = [
    {
      role: "Project Manager",
      email: "dravendrav213@gmail.com",
      phone: "9123456787",
    },
  ];

  return (
    <section>
      <div className={styles.tableHeader}>
        <div className={styles.tableHeaderLeft}>
          <div>Actions</div>
          <div>Name</div>
          <div>Email Address</div>
        </div>
        <div className={styles.tableHeaderRight}>
        </div>
      </div>  
    </section>
  );
}

export default UserTable;
