/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./UserManagement.module.css";
import SearchBar from "./SearchBar";
import UserTable from "./UserTable";

function UserManagement() {
  return (
    <main className={styles.container}>
      <header className={styles.header}>
        <div className={styles.titleWrapper}>
          <h1 className={styles.title} style={{fontSize:'2vmin'}}>Users</h1>
          <SearchBar />
        </div>
        <button className={styles.addButton}>Add Users</button>
      </header>
      <UserTable />
    </main>
  );
}

export default UserManagement;
