import React, { useState } from "react"; // Import useState from React
import Sidebar from "../SidebarComponents/Sidebar";
import styles from "./Storage.module.css";
import { Link } from "react-router-dom";
import { Dropdown, Button } from "react-bootstrap"; // Import Dropdown from react-bootstrap

const Reports = () => {
  // State for search inputs
  const [searchReportID, setSearchReportID] = useState("");
  const [searchReportType, setSearchReportType] = useState("");
  const [searchGeneratedBy, setSearchGeneratedBy] = useState("");
  const [searchDateGenerated, setSearchDateGenerated] = useState("");

  return (
    <div className={styles.dashboard}>
      <Sidebar />
      <main className={styles.mainContent} style={{ width: "100%" }}>
        <div className="d-flex justify-content-start">
          <ul className="nav nav-underline fs-6 me-3">
            <li className="nav-item pe-3">
              <Link
                to="/Storage" // Link to Products component
                className="nav-link fw-semibold text-decoration-none "
                style={{ color: "#6a6d71" }}
              >
                Products
              </Link>
            </li>
            <li className="nav-item pe-3">
              <Link
                to="/Storage/StockMovement" // Link to Inventory Approvals component
                className="nav-link fw-semibold text-decoration-none"
                style={{ color: "#6a6d71" }}
              >
                Stock Movement
              </Link>
            </li>
            <li className="nav-item">
              <Link
                to="/Storage/Reports" // Link to Reports component
                className="nav-link fw-semibold text-decoration-none border-bottom border-primary border-2"
              >
                Reports
              </Link>
            </li>
          </ul>
        </div>

        <div className="card shadow-sm py-3 px-4 mb-3">
          <div className="d-flex justify-content-between align-items-center">
            <div className="d-flex align-items-center">
              <i className="bi bi-bar-chart-fill fs-3"></i>
              <h5 className="fw-semibold ms-3 mb-0">Storage</h5>
            </div>
            <div>
              <Button
                onClick={() => handleModalShow()}
                className="btn btn-primary"
              >
                + Generate Reports
              </Button>
            </div>
          </div>
        </div>

        <div
          className="card shadow-sm px-4 py-1"
          style={{ backgroundColor: "#50504D" }}
        >
          {/* Dropdown for filtering by report type */}
          <div className="d-flex align-items-center" style={{ height: "50px" }}>
            <Dropdown>
              <Dropdown.Toggle variant="secondary" id="dropdown-basic">
                Report Type Filter
              </Dropdown.Toggle>
              <Dropdown.Menu>
                <Dropdown.Item eventKey="">All Reports</Dropdown.Item>
                <Dropdown.Item eventKey="Inventory">Inventory</Dropdown.Item>
                <Dropdown.Item eventKey="Sales">Sales</Dropdown.Item>
                <Dropdown.Item eventKey="Returns">Returns</Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>
        </div>

        <div className="card shadow-sm px-4 py-3">
          {/* Search Inputs in one line maximizing width */}
          <div className="row mb-3 g-3">
            <div className="col">
              <label htmlFor="searchReportID" style={{ fontSize: 13 }}>
                Report ID
              </label>
              <input
                type="text"
                id="searchReportID"
                className="form-control" // Use Bootstrap form-control for styling
                value={searchReportID}
                onChange={(e) => setSearchReportID(e.target.value)}
                style={{ borderColor: "blue", borderRadius: 50 }}
                placeholder="Report ID"
              />
            </div>
            <div className="col">
              <label htmlFor="searchReportType" style={{ fontSize: 13 }}>
                Report Type
              </label>
              <input
                type="text"
                id="searchReportType"
                className="form-control" // Use Bootstrap form-control for styling
                value={searchReportType}
                onChange={(e) => setSearchReportType(e.target.value)}
                style={{ borderColor: "blue", borderRadius: 50 }}
                placeholder="Type"
              />
            </div>
            <div className="col">
              <label htmlFor="searchGeneratedBy" style={{ fontSize: 13 }}>
                Generated By
              </label>
              <input
                type="text"
                id="searchGeneratedBy"
                className="form-control" // Use Bootstrap form-control for styling
                value={searchGeneratedBy}
                onChange={(e) => setSearchGeneratedBy(e.target.value)}
                style={{ borderColor: "blue", borderRadius: 50 }}
                placeholder="Name"
              />
            </div>
            <div className="col">
              <label htmlFor="searchDateGenerated" style={{ fontSize: 13 }}>
                Date Generated
              </label>
              <input
                type="date"
                id="searchDateGenerated"
                className="form-control" // Use Bootstrap form-control for styling
                value={searchDateGenerated}
                onChange={(e) => setSearchDateGenerated(e.target.value)}
                style={{ borderColor: "blue", borderRadius: 50 }}
              />
            </div>
          </div>

          {/* Table with sample content */}
          <div className="table-responsive">
            <table className="table table-hover border-top">
              <thead className="table-info">
                <tr>
                  <th scope="col" className="fw-semibold">
                    Report ID
                  </th>
                  <th scope="col" className="fw-semibold">
                    Report Type
                  </th>
                  <th scope="col" className="fw-semibold">
                    Generated By
                  </th>
                  <th scope="col" className="fw-semibold">
                    Date Generated
                  </th>
                  <th scope="col" className="fw-semibold">
                    Report Details
                  </th>
                </tr>
              </thead>
              <tbody className="fs-6 align-middle table-group-divider">
                <tr>
                  <td className="text-primary">R001</td>
                  <td className="text-primary">Inventory</td>
                  <td className="text-primary">Alice Smith</td>
                  <td className="text-primary">01/10/2024</td>
                  <td className="text-primary">
                    Overview of current inventory levels.
                  </td>
                </tr>
                <tr>
                  <td className="text-primary">R002</td>
                  <td className="text-primary">Sales</td>
                  <td className="text-primary">Bob Johnson</td>
                  <td className="text-primary">02/10/2024</td>
                  <td className="text-primary">
                    Sales summary for the month of September.
                  </td>
                </tr>
                <tr>
                  <td className="text-primary">R003</td>
                  <td className="text-primary">Returns</td>
                  <td className="text-primary">Charlie Brown</td>
                  <td className="text-primary">03/10/2024</td>
                  <td className="text-primary">
                    Details of returned items in the last week.
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Reports;
